"""
cross_speaker_summary.py
=========================
Reads the enriched XAI analysis CSVs (generated by paper_figure.py) for
m0001, m0002 and m0004, and produces:

  1. A publication-quality comparison table figure showing:
       Speaker | Top-1 | Top-2 | Top-3 | Attention Concentration
  2. A side-by-side phoneme ranking comparison (grouped bar / dot plot)
  3. A CSV summary table saved to xai_reddots/csv/

Usage:
    python3 xai_reddots/scripts/cross_speaker_summary.py
"""

import os
import csv
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.gridspec import GridSpec

# ─────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────
PHRASE_CLEAN = "my_voice_is_my_password"
CSV_DIR      = "xai_reddots/csv"
OUTPUT_DIR   = "xai_reddots/plots"
SPEAKERS     = ["m0001", "m0002", "m0004"]

BG       = '#ffffff'
PANEL_BG = '#fafafa'
GRID_COL = '#eeeeee'
SPINE_COL= '#cccccc'

# One distinct colour per speaker
SPK_COLORS = {
    'm0001': '#1a6b9a',   # steel blue
    'm0002': '#1a6b3c',   # forest green
    'm0004': '#6c3483',   # deep purple
}

LABEL_FS = 10
TICK_FS  = 8.5
TITLE_FS = 11
ANNOT_FS = 8.5


# ─────────────────────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────────────────────
def load_xai_csv(speaker_id):
    """
    Returns a list of dicts, one per phoneme, sorted by rank ascending.
    Fields: rank, phoneme, word, occurrence, start, end,
            start_frame, end_frame, mean_attention, std_attention,
            attention_pct, attention_pct_std
    """
    path = os.path.join(CSV_DIR,
                        f"{speaker_id}_{PHRASE_CLEAN}_xai_analysis.csv")
    if not os.path.exists(path):
        print(f"  [WARN] CSV not found for {speaker_id}: {path}")
        print(f"         Run:  python3 xai_reddots/scripts/paper_figure.py {speaker_id}")
        return None
    rows = []
    with open(path) as f:
        for row in csv.DictReader(f):
            rows.append({
                'rank':        int(row['rank']),
                'phoneme':     row['phoneme'],
                'word':        row['word'],
                'occurrence':  int(row['occurrence']),
                'start_frame': int(row['start_frame']),
                'end_frame':   int(row['end_frame']),
                'mean_attn':   float(row['mean_attention']),
                'std_attn':    float(row['std_attention']),
                'pct':         float(row['attention_pct']),
                'pct_std':     float(row['attention_pct_std']),
            })
    return sorted(rows, key=lambda r: r['rank'])


# ─────────────────────────────────────────────────────────────
# BUILD FIGURE
# ─────────────────────────────────────────────────────────────
def build_summary(data):
    """
    data: dict  speaker_id → list[phoneme_row]
    """
    fig = plt.figure(figsize=(16, 20), facecolor=BG)
    fig.suptitle(
        "Cross-Speaker ECAPA-TDNN Attention Analysis\n"
        "Phrase: \"My voice is my password\"",
        fontsize=14, fontweight='bold', y=0.995, color='#1a1a1a'
    )

    gs = GridSpec(3, 1, figure=fig,
                  height_ratios=[3.0, 6.0, 5.5],
                  hspace=0.52)

    # ── Panel (a): Speaker Comparison Table ──────────────────
    ax1 = fig.add_subplot(gs[0])
    ax1.set_facecolor(PANEL_BG)
    ax1.axis('off')
    ax1.set_title("(a)  Cross-Speaker Attention Summary Table",
                  fontsize=TITLE_FS, fontweight='bold', loc='left', pad=8)

    # Build table data
    col_headers = ['Speaker', 'n recs', 'Top-1 Phoneme', 'Pct',
                   'Top-2 Phoneme', 'Pct',
                   'Top-3 Phoneme', 'Pct',
                   'Top-3 Conc.', 'Pearson r']
    table_rows  = []

    # Load Pearson r from the main CSV (not stored yet — read from console)
    # We'll compute concentration from the data directly
    pearson_r = {
        'm0001': -0.180,   # from paper_figure.py output
        'm0002': +0.680,
        'm0004': +0.571,
    }
    n_recs = {
        'm0001': 31,
        'm0002': 29,
        'm0004': 6,
    }

    summary_export = []   # for CSV export
    all_top3_phonemes = {}   # speaker → [phoneme symbols]

    for sid in SPEAKERS:
        rows = data.get(sid)
        if rows is None:
            continue
        top3 = rows[:3]
        conc = sum(r['pct'] for r in top3)
        table_rows.append([
            sid,
            str(n_recs.get(sid, '?')),
            top3[0]['phoneme'], f"{top3[0]['pct']:.1f}%",
            top3[1]['phoneme'], f"{top3[1]['pct']:.1f}%",
            top3[2]['phoneme'], f"{top3[2]['pct']:.1f}%",
            f"{conc:.1f}%",
            f"{pearson_r.get(sid, 0):+.3f}",
        ])
        all_top3_phonemes[sid] = [r['phoneme'] for r in top3]
        summary_export.append({
            'speaker':          sid,
            'n_recordings':     n_recs.get(sid, '?'),
            'top1_phoneme':     top3[0]['phoneme'],
            'top1_word':        top3[0]['word'],
            'top1_pct':         f"{top3[0]['pct']:.2f}",
            'top2_phoneme':     top3[1]['phoneme'],
            'top2_word':        top3[1]['word'],
            'top2_pct':         f"{top3[1]['pct']:.2f}",
            'top3_phoneme':     top3[2]['phoneme'],
            'top3_word':        top3[2]['word'],
            'top3_pct':         f"{top3[2]['pct']:.2f}",
            'top3_concentration': f"{conc:.2f}",
            'pearson_r':        f"{pearson_r.get(sid, 0):+.4f}",
        })

    # Draw table
    col_widths = [0.07, 0.06, 0.10, 0.07, 0.10, 0.07, 0.10, 0.07, 0.09, 0.09]
    x_starts   = [sum(col_widths[:i]) for i in range(len(col_widths))]
    x_total    = sum(col_widths)
    row_h      = 0.18
    header_y   = 0.90

    # Header row
    for xi, (hdr, cw) in enumerate(zip(col_headers, col_widths)):
        ax1.text(x_starts[xi] + cw / 2, header_y, hdr,
                 ha='center', va='center', fontsize=9,
                 fontweight='bold', color='white',
                 transform=ax1.transAxes)
    ax1.add_patch(patches.FancyBboxPatch(
        (0, header_y - row_h * 0.55), x_total, row_h * 0.9,
        boxstyle='round,pad=0.005',
        facecolor='#2c3e50', edgecolor='none',
        transform=ax1.transAxes, clip_on=False))

    # Data rows
    row_colors = ['#f0f4f8', '#ffffff']
    for ri, (sid, row) in enumerate(zip(SPEAKERS, table_rows)):
        ry = header_y - (ri + 1) * row_h
        ax1.add_patch(patches.FancyBboxPatch(
            (0, ry - row_h * 0.45), x_total, row_h * 0.88,
            boxstyle='round,pad=0.003',
            facecolor=row_colors[ri % 2], edgecolor=SPINE_COL, linewidth=0.5,
            transform=ax1.transAxes, clip_on=False))
        # Speaker ID coloured
        ax1.text(x_starts[0] + col_widths[0] / 2, ry, row[0],
                 ha='center', va='center', fontsize=9.5, fontweight='bold',
                 color=SPK_COLORS[sid], transform=ax1.transAxes)
        # Rest of cells
        for xi in range(1, len(row)):
            # Highlight top-phoneme cells
            cell_color = '#1a1a1a'
            cell_fw    = 'normal'
            if xi in (2, 4, 6):   # phoneme columns
                cell_color = '#333333'
                cell_fw    = 'bold'
            if xi in (8,):        # concentration column
                cell_fw = 'semibold'
            ax1.text(x_starts[xi] + col_widths[xi] / 2, ry, row[xi],
                     ha='center', va='center', fontsize=9,
                     color=cell_color, fontweight=cell_fw,
                     transform=ax1.transAxes)

    # ── Panel (b): Full Phoneme Ranking Comparison ────────────
    ax2 = fig.add_subplot(gs[1])
    ax2.set_facecolor(PANEL_BG)
    ax2.grid(True, ls='--', color=GRID_COL, alpha=0.9, linewidth=0.7, axis='x')
    for sp in ax2.spines.values():
        sp.set_color(SPINE_COL);  sp.set_linewidth(0.8)
    ax2.set_title("(b)  Full Phoneme Attention % — All Speakers Side-by-Side",
                  fontsize=TITLE_FS, fontweight='bold', loc='left', pad=8)

    # Gather all unique phoneme labels across all speakers (in order of m0004's ranking)
    ref_spk   = 'm0004'
    ref_rows  = data.get(ref_spk, [])
    all_labels= [f"{r['word']}: /{r['phoneme']}/" for r in ref_rows]

    # For each label, get pct for each speaker (0 if not present)
    label_to_pct = {}
    for sid, rows in data.items():
        if rows is None:
            continue
        for r in rows:
            lbl = f"{r['word']}: /{r['phoneme']}/"
            if lbl not in label_to_pct:
                label_to_pct[lbl] = {}
            label_to_pct[lbl][sid] = r['pct']

    # Sort labels by m0004 pct descending (top attention at top)
    sorted_labels = sorted(all_labels,
                           key=lambda l: label_to_pct.get(l, {}).get('m0004', 0),
                           reverse=True)

    n_labels = len(sorted_labels)
    n_spk    = len(SPEAKERS)
    bar_h    = 0.22
    group_h  = bar_h * n_spk + 0.08
    y_positions = np.arange(n_labels) * group_h

    for si, sid in enumerate(SPEAKERS):
        pcts_bar = [label_to_pct.get(lbl, {}).get(sid, 0) for lbl in sorted_labels]
        y_off    = (si - n_spk / 2 + 0.5) * bar_h
        bars = ax2.barh(y_positions + y_off, pcts_bar,
                        height=bar_h * 0.88,
                        color=SPK_COLORS[sid], alpha=0.80,
                        edgecolor='white', linewidth=0.3,
                        label=sid)

    ax2.set_yticks(y_positions)
    ax2.set_yticklabels(sorted_labels, fontsize=TICK_FS)
    ax2.set_xlabel("Attention share (%)", fontsize=LABEL_FS)
    ax2.tick_params(axis='y', labelsize=TICK_FS)
    ax2.legend(loc='lower right', fontsize=ANNOT_FS, framealpha=0.75,
               title='Speaker', title_fontsize=ANNOT_FS)
    ax2.invert_yaxis()   # top = highest attention

    # ── Panel (c): Attention Concentration Bar ────────────────
    ax3 = fig.add_subplot(gs[2])
    ax3.set_facecolor(PANEL_BG)
    ax3.grid(True, ls='--', color=GRID_COL, alpha=0.9, linewidth=0.7, axis='x')
    for sp in ax3.spines.values():
        sp.set_color(SPINE_COL);  sp.set_linewidth(0.8)
    ax3.set_title(
        "(c)  Top-3 Phoneme Attention Concentration per Speaker\n"
        "      [Higher = model attention more focused on fewer phonemes]",
        fontsize=TITLE_FS, fontweight='bold', loc='left', pad=8)

    for si, sid in enumerate(SPEAKERS):
        rows = data.get(sid)
        if rows is None:
            continue
        top3     = rows[:3]
        conc     = sum(r['pct'] for r in top3)
        rest     = 100.0 - conc
        ax3.barh(si, conc, color=SPK_COLORS[sid], alpha=0.85,
                 height=0.45, label=f"{sid}  (top-3 = {conc:.1f}%)")
        ax3.barh(si, rest, left=conc,
                 color=SPK_COLORS[sid], alpha=0.20, height=0.45,
                 hatch='////', edgecolor=SPK_COLORS[sid], linewidth=0.4)
        # Phoneme labels inside bar
        x_cursor = 0
        for ri, r in enumerate(top3):
            seg_w  = r['pct']
            mid_x  = x_cursor + seg_w / 2
            ax3.text(mid_x, si,
                     f"/{r['phoneme']}/\n{r['pct']:.1f}%",
                     ha='center', va='center',
                     fontsize=8.5 if seg_w > 3.5 else 6.5,
                     color='white', fontweight='bold')
            if ri < 2:
                ax3.axvline(x_cursor + seg_w, color='white',
                            lw=1.0, ymin=(si) / n_spk + 0.02,
                            ymax=(si + 1) / n_spk - 0.02, alpha=0.6)
            x_cursor += seg_w
        # "Rest" label
        ax3.text(conc + rest / 2, si, f"rest\n{rest:.1f}%",
                 ha='center', va='center', fontsize=8, color='#666666')

    ax3.set_yticks(range(n_spk))
    ax3.set_yticklabels(SPEAKERS, fontsize=LABEL_FS, fontweight='bold')
    ax3.set_xlim(0, 110)
    ax3.set_xlabel("Cumulative attention share (%)", fontsize=LABEL_FS)
    ax3.legend(loc='lower right', fontsize=ANNOT_FS, framealpha=0.75)
    ax3.axvline(100, color='#888', lw=0.8, ls=':')

    plt.tight_layout(rect=[0, 0, 1, 0.994])
    return fig, summary_export


# ─────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────
def main():
    data = {}
    for sid in SPEAKERS:
        print(f"Loading {sid}…")
        data[sid] = load_xai_csv(sid)

    missing = [s for s, d in data.items() if d is None]
    if missing:
        print(f"\n[ERROR] Missing enriched CSVs for: {missing}")
        print("  Run paper_figure.py for each missing speaker first.")
        sys.exit(1)

    print("\nBuilding cross-speaker summary figure…")
    fig, summary_export = build_summary(data)

    # Save figure
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    fig_path = os.path.join(OUTPUT_DIR,
                            f"cross_speaker_{PHRASE_CLEAN}_summary.png")
    fig.savefig(fig_path, dpi=300, bbox_inches='tight',
                facecolor=fig.get_facecolor(), edgecolor='none')
    plt.close(fig)
    print(f"✓  Figure → {fig_path}")

    # Save summary CSV
    summary_csv = os.path.join(CSV_DIR,
                               f"cross_speaker_{PHRASE_CLEAN}_summary.csv")
    fields = ['speaker', 'n_recordings',
              'top1_phoneme', 'top1_word', 'top1_pct',
              'top2_phoneme', 'top2_word', 'top2_pct',
              'top3_phoneme', 'top3_word', 'top3_pct',
              'top3_concentration', 'pearson_r']
    with open(summary_csv, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(summary_export)
    print(f"✓  Summary CSV → {summary_csv}")

    # Print table to console
    print("\n" + "=" * 70)
    print(f"{'Speaker':<10} {'Top-1':>8} {'Top-2':>8} {'Top-3':>8} {'Conc.':>8}  r")
    print("-" * 70)
    for row in summary_export:
        print(f"{row['speaker']:<10} "
              f"{row['top1_phoneme']+' '+row['top1_pct']+'%':>10} "
              f"{row['top2_phoneme']+' '+row['top2_pct']+'%':>10} "
              f"{row['top3_phoneme']+' '+row['top3_pct']+'%':>10} "
              f"{row['top3_concentration']+'%':>8}  "
              f"{row['pearson_r']}")
    print("=" * 70)


if __name__ == '__main__':
    main()
