"""
regen_averaged_aligned.py
=========================
Regenerates the averaged figure for m0004 / my_voice_is_my_password using
SPEECH-SPAN-ALIGNED averaging:

  For each recording:
    1. Detect speech onset/offset with our improved two-threshold VAD
    2. Apply affine remap: t_avg = mfa_onset + (t_rec - onset)/(offset - onset)
                                              × (mfa_offset - mfa_onset)
    3. Resample attention / RMS / Mel to the common MFA-aligned time axis

  This ensures that phoneme boundaries (from MFA) correctly overlay the
  averaged acoustic energy, regardless of different lead-in silences per
  recording.

Additionally the representative waveform (shown in Panel A) is DC-removed
so no artifact decays are visible.
"""

import os, sys, json, csv, warnings
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

sys.path.append(os.getcwd())

from xai_reddots.scripts.plot_individual_recordings import detect_speech_span
from xai_reddots.scripts.final_figure import (
    load_model, build_figure, extract_attention, rms_envelope, mel_spec,
    SR, HOP, N_MELS
)
import soundfile as sf

# ── Config ────────────────────────────────────────────────────────────────────
SPEAKER    = sys.argv[1] if len(sys.argv) > 1 else 'm0004'
PHRASE_KEY = 'my_voice_is_my_password'

# Use the timeline generated by the batch pipeline
MFA_TL = f'xai_reddots/results/phrase1_{PHRASE_KEY}/timelines/{SPEAKER}_timeline.json'
if not os.path.exists(MFA_TL):
    if SPEAKER == 'm0001':
        MFA_TL = 'xai_reddots/metadata/timeline.json'
    else:
        MFA_TL = f'xai_reddots/metadata/{SPEAKER}_{PHRASE_KEY}_timeline.json'

CSV_META   = f'xai_reddots/metadata/separated_phrases/{PHRASE_KEY}.csv'
OUT_DIR    = f'xai_reddots/results/phrase1_{PHRASE_KEY}/plots'
CSV_DIR    = f'xai_reddots/results/phrase1_{PHRASE_KEY}/csv'


def dc_remove(audio, cutoff_sec=0.05, sr=SR):
    """Remove DC offset using a high-pass filter (subtract running mean over 50ms)."""
    win = max(1, int(cutoff_sec * sr))
    kernel = np.ones(win) / win
    dc = np.convolve(audio.astype(float), kernel, mode='same')
    return (audio.astype(float) - dc).astype(audio.dtype)


def main():
    # ── Load MFA timeline ─────────────────────────────────────────────────────
    with open(MFA_TL) as f:
        tdata = json.load(f)

    phonemes   = tdata['phonemes']
    mfa_onset  = float(phonemes[0]['start'])   # e.g. 1.095 s
    mfa_offset = float(phonemes[-1]['end'])     # e.g. 2.834 s
    avg_dur    = float(tdata.get('avg_duration_sec', 3.791))

    print(f"MFA speech span  : {mfa_onset:.3f}s → {mfa_offset:.3f}s")
    print(f"Average duration : {avg_dur:.3f}s")

    # ── Load recording paths ──────────────────────────────────────────────────
    recs = []
    with open(CSV_META) as f:
        for row in csv.DictReader(f):
            if row['speaker_id'] == SPEAKER and os.path.exists(row['pcm_path']):
                recs.append(row['pcm_path'])
    print(f"Found {len(recs)} recordings for {SPEAKER}")

    # ── Load model ────────────────────────────────────────────────────────────
    print("Loading model...")
    model = load_model()

    # Determine profile length P from the first recording
    prof0, _ = extract_attention(model, recs[0])
    P = len(prof0)
    prof_t = np.linspace(0, avg_dur, P)   # shared time axis (MFA-aligned)

    # ── Per-recording aligned extraction ──────────────────────────────────────
    all_profs, all_rms, all_mel = [], [], []
    rep_audio = None

    for idx, path in enumerate(recs, 1):
        print(f"\n  Rec {idx}/{len(recs)}: {os.path.basename(path)}")
        try:
            audio, _ = sf.read(path, channels=1, samplerate=SR,
                                subtype='PCM_16', format='RAW')
            dur = len(audio) / SR

            # ── Step 1: detect speech span ────────────────────────────────
            rec_onset, rec_offset = detect_speech_span(audio, sr=SR, hop=HOP)
            print(f"    VAD: onset={rec_onset:.3f}s  offset={rec_offset:.3f}s")

            # ── Step 2: compute affine scale ──────────────────────────────
            #   t_rec = rec_onset + (t_avg - mfa_onset) * scale
            speech_dur_rec = max(rec_offset - rec_onset, 0.01)
            speech_dur_mfa = max(mfa_offset - mfa_onset, 0.01)
            scale = speech_dur_rec / speech_dur_mfa

            # Save first rec as representative waveform for Panel A:
            #   DC-remove + affine-remap to MFA time axis so speech sits at mfa_onset
            if rep_audio is None:
                clean = dc_remove(audio)
                # Build a time axis for the rep audio at SR samples
                t_rep_src = np.linspace(0, dur, len(clean))
                # Build the output time axis at SR resolution
                t_out = np.arange(0, avg_dur, 1.0 / SR)
                # Inverse affine: t_rec = rec_onset + (t_avg - mfa_onset) * scale
                t_rec_mapped = rec_onset + (t_out - mfa_onset) * scale
                t_rec_mapped = np.clip(t_rec_mapped, 0.0, dur)
                # Zero out samples before mfa_onset (pre-speech silence)
                aligned_wave = np.interp(t_rec_mapped, t_rep_src, clean.astype(float))
                aligned_wave[t_out < mfa_onset] = 0.0
                rep_audio = aligned_wave

            # ── Step 3: extract attention profile ────────────────────────
            prof, _ = extract_attention(model, path)
            src_t_prof = np.linspace(0, dur, len(prof))

            prof_t_rec = rec_onset + (prof_t - mfa_onset) * scale
            prof_t_rec = np.clip(prof_t_rec, 0.0, dur)

            # ── Step 4: resample to common time axis ─────────────────────
            aligned_prof = np.interp(prof_t_rec, src_t_prof, prof)
            all_profs.append(aligned_prof)

            rms = rms_envelope(audio)
            src_t_rms = np.linspace(0, dur, len(rms))
            all_rms.append(np.interp(prof_t_rec, src_t_rms, rms))

            an = audio / (np.max(np.abs(audio)) + 1e-9)
            mP = mel_spec(an)
            src_t_mel = np.linspace(0, dur, mP.shape[1])
            mi = np.zeros((N_MELS, P))
            for fi in range(N_MELS):
                mi[fi] = np.interp(prof_t_rec, src_t_mel, mP[fi])
            all_mel.append(mi)

        except Exception as e:
            print(f"    ERROR: {e}")
            import traceback; traceback.print_exc()

    if not all_profs:
        print("No profiles collected — aborting.")
        return

    # ── Average ───────────────────────────────────────────────────────────────
    all_profs = np.vstack(all_profs)
    mean_prof = np.mean(all_profs, 0)
    std_prof  = np.std(all_profs, 0)
    mean_rms  = np.mean(all_rms, 0)
    rms_norm  = mean_rms / (np.max(mean_rms) + 1e-9)
    mel_db    = 10 * np.log10(np.mean(all_mel, 0) + 1e-10)

    # Force silence outside MFA bounds to remove time-stretched background noise
    # This prevents Panel B from showing thick noise bands before speech starts.
    silence_mask = (prof_t < mfa_onset) | (prof_t > mfa_offset)
    rms_norm[silence_mask] = 0.0
    mel_db[:, silence_mask] = np.min(mel_db)

    # ── Phoneme statistics ────────────────────────────────────────────────────
    occ = {ph['phoneme']: sum(1 for p in phonemes if p['phoneme'] == ph['phoneme'])
           for ph in phonemes}
    ph_data = []
    for ph in phonemes:
        s, e = float(ph['start']), float(ph['end'])
        mask = (prof_t >= s) & (prof_t <= e)
        if not np.any(mask):
            ci = np.argmin(np.abs(prof_t - (s + e) / 2))
            mask = np.zeros(P, bool); mask[ci] = True
        vals = np.array([np.mean(all_profs[r, mask])
                         for r in range(all_profs.shape[0])])
        rms_ph = float(np.mean(rms_norm[mask])) if np.any(mask) else 0.0
        ph_data.append({
            'phoneme':  ph['phoneme'],
            'word':     ph['word'],
            'start':    s, 'end': e,
            'start_frame': int(round(s * 100)),
            'end_frame':   int(round(e * 100)),
            'occurrence': occ[ph['phoneme']],
            'mean':  float(np.mean(vals)),
            'std':   float(np.std(vals)),
            'rms':   rms_ph,
        })

    total = sum(p['mean'] for p in ph_data) or 1e-12
    for rank_i, p in enumerate(sorted(ph_data, key=lambda x: x['mean'], reverse=True), 1):
        p['pct'] = p['mean'] / total * 100
        p['rank'] = rank_i
    rm = {(p['phoneme'], round(p['start'], 4)): (p['pct'], p['rank']) for p in ph_data}
    for p in ph_data:
        p['pct'], p['rank'] = rm[(p['phoneme'], round(p['start'], 4))]

    top3_pct   = sum(p['pct'] for p in sorted(ph_data, key=lambda x: x['rank'])[:3])
    corr       = float(np.corrcoef(mean_rms, mean_prof)[0, 1])
    peak_idx   = int(np.argmax(mean_prof))
    peak_val   = float(mean_prof[peak_idx])
    peak_time  = float(prof_t[peak_idx])
    peak_frame = int(round(peak_time * 100))

    # Word boundaries
    word_bounds = []
    curr_word = None; w_start = 0; w_end = 0
    for ph in phonemes:
        w = ph['word']
        if curr_word is None:
            curr_word = w; w_start = ph['start']; w_end = ph['end']
        elif w == curr_word:
            w_end = max(w_end, ph['end'])
        else:
            word_bounds.append((curr_word, [w_start, w_end]))
            curr_word = w; w_start = ph['start']; w_end = ph['end']
    if curr_word is not None:
        word_bounds.append((curr_word, [w_start, w_end]))

    d = dict(
        avg_dur=avg_dur, prof_t=prof_t,
        mean_prof=mean_prof, std_prof=std_prof,
        mean_rms=mean_rms, rms_norm=rms_norm, mel_db=mel_db,
        phonemes=phonemes, ph_data=ph_data, total=total,
        word_bounds=word_bounds, top3_pct=top3_pct, corr=corr,
        n_recs=len(all_profs),
        peak_val=peak_val, peak_time=peak_time, peak_frame=peak_frame,
        rep_audio=rep_audio,
    )

    # ── Build & save figure ───────────────────────────────────────────────────
    phrase_title = tdata.get('phrase', 'My Voice is My Password')
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        fig = build_figure(SPEAKER, d, phrase_title)

    os.makedirs(OUT_DIR, exist_ok=True)
    fig_path = os.path.join(OUT_DIR, f"{SPEAKER}_{PHRASE_KEY}_final_figure.png")
    fig.savefig(fig_path, dpi=300, bbox_inches='tight',
                facecolor=fig.get_facecolor(), edgecolor='none')
    plt.close(fig)
    print(f"\n✓  Figure → {fig_path}")

    # ── Save CSV ──────────────────────────────────────────────────────────────
    os.makedirs(CSV_DIR, exist_ok=True)
    csv_path = os.path.join(CSV_DIR, f"{SPEAKER}_{PHRASE_KEY}_xai_analysis.csv")
    fields = ['rank', 'phoneme', 'word', 'start', 'end',
              'start_frame', 'end_frame', 'occurrence',
              'mean_attention', 'std_attention', 'attention_pct', 'attention_pct_std']
    with open(csv_path, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for p in sorted(ph_data, key=lambda x: x['rank']):
            w.writerow({
                'rank':              p['rank'],
                'phoneme':           p['phoneme'],
                'word':              p['word'],
                'start':             f"{p['start']:.4f}",
                'end':               f"{p['end']:.4f}",
                'start_frame':       p['start_frame'],
                'end_frame':         p['end_frame'],
                'occurrence':        p['occurrence'],
                'mean_attention':    f"{p['mean']:.6f}",
                'std_attention':     f"{p['std']:.6f}",
                'attention_pct':     f"{p['pct']:.4f}",
                'attention_pct_std': f"{p['std']/total*100:.4f}",
            })
    print(f"✓  CSV    → {csv_path}")

    top3 = sorted(ph_data, key=lambda x: x['rank'])[:3]
    top3_str = ' | '.join(f"{p['phoneme']} {p['pct']:.1f}%" for p in top3)
    print(f"   Top-3: {top3_str}")
    print(f"   Concentration: {top3_pct:.1f}%")
    print(f"   Peak: {peak_val:.5f} at {peak_time:.2f}s (frame {peak_frame})")
    print(f"   Pearson r: {corr:+.4f}")
    print(f"   Recordings: {len(all_profs)}")


if __name__ == '__main__':
    main()
